version: "3"
services:
    proxy:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8008:80"
        depends_on: 
            - api
        restart: always
    api:
        build: . 
        restart: always
        ports: 
            - "5000"